
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}
spec:
  replicas: 1
  selector:
    app: ${NAME}
    deploymentconfig: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
        deploymentconfig: ${NAME}
    spec:
      containers:
      - env:
        - name: DOCUMENTROOT
          value: /public
        - name: APP_URL
          value: ${APP_URL}
        - name: APP_DEBUG
          value: ${APP_DEBUG}
        - name: APP_ENV
          value: ${APP_ENV}
        - name: DB_HOST
          value: ${DB_HOST}
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql
        - name: APP_LOG
          value: errorlog
        - name: QUEUE_DRIVER
          value: database
        - name: APP_KEY
          value: ${APP_KEY}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql
        image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
        imagePullPolicy: Always
        name: ${NAME}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - ${NAME}
      from:
        kind: ImageStreamTag
        name: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    type: ImageChange
  - type: ConfigChange